modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "bubbleschunkgen"
version = "${version}"
displayName = "BubblesOnChunkGen"
description = "Triggers block updates on soul_sand under water after chunk generation to create bubble columns."

[[dependencies.bubbleschunkgen]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.bubbleschunkgen]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "SERVER"
